### PR TITLE
Rebase to master and add test

### PR DESCRIPTION
**Pull request by diega**
Hi!
I was about to make a pull request to `vert-x3/vertx-rabbitmq-client` about implementing _basicAck_ when I saw yours. As both solutions were pretty identical I thought it would be better to merge my additions into your own branch (if you accept them) so it gets reflected into the original pull request.

Regards.

ps= I also rebased to master to keep the history a little cleaner

### CODE REVIEW

**Comment by diega** [comment]
Hi @w0mbat did you have some time to review it? I think we can get a real chance of getting this merged into the official branch if there are more than one dev involved :)

**Comment by w0mbat** [comment]
hi @diega, sorry for missing this one for a couple of days.
Was pretty busy traveling :/

lgtm :)

**Comment by w0mbat** [comment]
As far as I get it, my original pull-request won´t be extended, because its a different branch.

**Comment by diega** [comment]
Awesome, thank you for having the time for checking this.
Yes, you are right, now I don't remember why I've made this PR against `master` instead of `initial-work`. Anyway, I think there are two options, you can close [your current PR](https://github.com/vert-x3/vertx-rabbitmq-client/pull/2) and create a new one or you can _force_ a rebase of `initial-work` to `master` but you would need to edit the current PR to be applied against `master` (Idk if it's possible on github, it is on bitbucket).
Anything I can do for helping you (beside requesting politely a review of the PR) just let me know.

Regards!

**Pull request merged**
